apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: db
  name: db
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-3"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - env:
            - name: MARIADB_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: DB_DATABASE
                  name: env-docker
            - name: MARIADB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: DB_PASSWORD
                  name: env-docker
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: MARIADB_ROOT_PASSWORD
                  name: env-docker
            - name: MARIADB_USER
              valueFrom:
                configMapKeyRef:
                  key: DB_USERNAME
                  name: env-docker
          image: mariadb:lts
          name: db
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: db-data
      restartPolicy: Always
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: db-data
