apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: db-data
  name: db-data
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-3"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
