apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nginx
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: nginx
    spec:
      containers:
        - image: hfhnom/stvpl-nginx:latest
          name: nginx
          volumeMounts:
          - name: nginx-config-volume
            mountPath: /etc/nginx/conf.d
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
      volumes:
      - name: nginx-config-volume
        configMap:
          name: nginx-config
